/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 *
 * @author Felipe
 */
public class Cerrar_caja extends javax.swing.JFrame {

    /**
     * Creates new form Cerrar_caja
     */
    public Cerrar_caja() {
        initComponents();
        alineacion();
       
    }
     DecimalFormat formateador = new DecimalFormat("###,###.##");
    
    public void alineacion()
    {
        txt20.setText("0");
        Txt10.setText("0");
        txt5.setText("0");
        txt2.setText("0");
        txt1.setText("0");
        txtkina.setText("0");
        txtgamba.setText("0");
        txt50.setText("0");
        txtdiez.setText("0");
        txtTotal.setText("0");
        txt20.setHorizontalAlignment(txt20.RIGHT);
        Txt10.setHorizontalAlignment(Txt10.RIGHT);
        txt5.setHorizontalAlignment(txt5.RIGHT);
        txt2.setHorizontalAlignment(txt2.RIGHT);
        txt1.setHorizontalAlignment(txt1.RIGHT);
        txtkina.setHorizontalAlignment(txtkina.RIGHT);
        txtgamba.setHorizontalAlignment(txtgamba.RIGHT);
        txt50.setHorizontalAlignment(txt50.RIGHT);
        txtdiez.setHorizontalAlignment(txtdiez.RIGHT);
        txtTotal.setHorizontalAlignment(txtTotal.RIGHT);
       
    }
    public void SumaTotal()
    {
       
           try{
            int n20=Integer.parseInt(this.txt20.getText());
            int n10=Integer.parseInt(this.Txt10.getText());
            int n5 =Integer.parseInt(this.txt5.getText());
            int n2 =Integer.parseInt(this.txt2.getText());
            int n1 =Integer.parseInt(this.txt1.getText());
            int n500=Integer.parseInt(this.txtkina.getText());
            int n100=Integer.parseInt(this.txtgamba.getText());
            int n50=Integer.parseInt(this.txt50.getText());
            int ndiez=Integer.parseInt(this.txtdiez.getText());
            int suma=(n20+n10+n5+n2+n1+n500+n100+n50+ndiez);            
            txtTotal.setText("$ "+formateador.format(suma));
           }
           catch(NumberFormatException e){
               System.out.println("error");
           }        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtkina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtgamba = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt50 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdiez = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt20 = new javax.swing.JTextField();
        Txt10 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("10.000");

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        jLabel3.setText("5.000");

        txtkina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkinaActionPerformed(evt);
            }
        });
        txtkina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkinaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkinaKeyTyped(evt);
            }
        });

        jLabel4.setText("2.000");

        txtgamba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgambaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgambaKeyTyped(evt);
            }
        });

        jLabel5.setText("1.000");

        txt50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt50KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt50KeyTyped(evt);
            }
        });

        jLabel6.setText("500");

        jLabel9.setText("50");

        jLabel7.setText("100");

        txtdiez.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiezKeyPressed(evt);
            }
        });

        jLabel8.setText("10");

        txt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt20ActionPerformed(evt);
            }
        });
        txt20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt20KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt20KeyTyped(evt);
            }
        });

        Txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt10ActionPerformed(evt);
            }
        });
        Txt10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt10KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt10KeyTyped(evt);
            }
        });

        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt5KeyTyped(evt);
            }
        });

        jLabel1.setText("20.000");

        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });

        jLabel10.setText("Total:");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Cuadratura");

        txtTotal.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(36, 36, 36)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 76, Short.MAX_VALUE))
                            .addComponent(txt20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txt10)
                            .addComponent(txt5)
                            .addComponent(txt2)
                            .addComponent(txt1)
                            .addComponent(txtkina)
                            .addComponent(txtgamba)
                            .addComponent(txt50)
                            .addComponent(txtdiez))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtgamba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt20ActionPerformed

    private void Txt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt10ActionPerformed

    private void txt20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyTyped
      char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();       
    
    }//GEN-LAST:event_txt20KeyTyped

    private void txt20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyPressed
     if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      try{
      int resultado=0;
      resultado = (Integer.parseInt(this.txt20.getText())*20000);
      txt20.setText(String.valueOf(resultado));
      Txt10.requestFocus();
      SumaTotal();
      }
      catch(NumberFormatException e){System.out.println("falla txt20");}
      
     }
              
    }//GEN-LAST:event_txt20KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Txt10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt10KeyTyped
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();            
        
    }//GEN-LAST:event_Txt10KeyTyped

    private void Txt10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt10KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      int resultado=0;
      resultado = (Integer.parseInt(this.Txt10.getText())*10000);
      Txt10.setText(String.valueOf(resultado));
      txt5.requestFocus();
      SumaTotal();      
      }
    }//GEN-LAST:event_Txt10KeyPressed

    private void txt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      int resultado=0;
      resultado = (Integer.parseInt(this.txt5.getText())*5000);
      txt5.setText(String.valueOf(resultado));
      txt2.requestFocus();
      SumaTotal();
      }
    }//GEN-LAST:event_txt5KeyPressed

    private void txt5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();            
        
    }//GEN-LAST:event_txt5KeyTyped

    private void txt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      int resultado=0;
      resultado = (Integer.parseInt(this.txt2.getText())*2000);
      txt2.setText(String.valueOf(resultado));
      txt1.requestFocus();
      SumaTotal();
      }
    }//GEN-LAST:event_txt2KeyPressed

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txt2KeyTyped

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      int resultado=0;
      resultado = (Integer.parseInt(this.txt1.getText())*1000);
      txt1.setText(String.valueOf(resultado));
      txtkina.requestFocus();
      SumaTotal();
      }
    }//GEN-LAST:event_txt1KeyPressed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txt1KeyTyped

    private void txtkinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkinaKeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      int resultado=0;
      resultado = (Integer.parseInt(this.txtkina.getText())*500);
      txtkina.setText(String.valueOf(resultado));
      txtgamba.requestFocus();
      SumaTotal();
      }
    }//GEN-LAST:event_txtkinaKeyPressed

    private void txtkinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkinaKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtkinaKeyTyped

    private void txtgambaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgambaKeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
      int resultado=0;
      resultado = (Integer.parseInt(this.txtgamba.getText())*100);
      txtgamba.setText(String.valueOf(resultado));
      txt50.requestFocus();
      SumaTotal();
      }
    }//GEN-LAST:event_txtgambaKeyPressed

    private void txtgambaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgambaKeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtgambaKeyTyped

    private void txt50KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyTyped
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if (c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txt50KeyTyped

    private void txt50KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int resultado=0;
            resultado = (Integer.parseInt(this.txt50.getText())*50);
            txt50.setText(String.valueOf(resultado));
            txtdiez.requestFocus();
            SumaTotal();
        }
    }//GEN-LAST:event_txt50KeyPressed

    private void txtdiezKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiezKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int resultado=0;
            resultado = (Integer.parseInt(this.txtdiez.getText())*10);
            txtdiez.setText(String.valueOf(resultado));
            SumaTotal();

        }
    }//GEN-LAST:event_txtdiezKeyPressed

    private void txtkinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cerrar_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cerrar_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cerrar_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cerrar_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cerrar_caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txt10;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtdiez;
    private javax.swing.JTextField txtgamba;
    private javax.swing.JTextField txtkina;
    // End of variables declaration//GEN-END:variables
}
